version: '3.8'
services:
  cliente-db:
    image: postgres:15
    environment:
      POSTGRES_DB: clientedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  cliente-service:
    build: ./cliente-service
    ports:
      - "8081:8080"
    environment:
      DB_HOST: cliente-db
    depends_on:
      - cliente-db